[tool.uv.workspace]
members = ["backend"]

[project]
name = "hotel-guest-assistant"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "backend",
    "fastembed>=0.8.1",
    "qdrant-client>=1.19.1",
]

[tool.uv.sources]
backend = { workspace = true }

[project.scripts]
backend = "app.main:start"
