import json
import math
import re
from collections import Counter
from pathlib import Path
from typing import Any, Dict, List, Optional
import numpy as np

from app.config import settings
from app.core.chunker import SemanticHotelChunker, SemanticChunk

BASE_DIR = Path(__file__).resolve().parent.parent
HOTEL_DATA_FILE = BASE_DIR / "data" / "hotel_data.json"

STOPWORDS = {
    "the", "is", "at", "which", "on", "a", "an", "this", "that", "to", "of",
    "for", "with", "does", "do", "you", "have", "can", "what", "where", "how",
    "are", "about", "hotel", "resort", "grand", "azure", "tell", "me", "any",
    "please", "i", "we", "my", "our", "would", "like", "if", "yes", "no", "so",
    "when", "why", "who", "want", "need", "could", "should", "there", "also"
}

SYNONYMS = {
    "cancel": ["cancellation", "cancellations", "cancelling", "cancelled", "refund"],
    "cancellation": ["cancel", "cancelling", "cancelled", "refund"],
    "cancelling": ["cancel", "cancellation"],
    "reservation": ["booking", "bookings", "reserve", "reservations"],
    "reserve": ["reservation", "booking", "reservations"],
    "booking": ["reservation", "reserve", "bookings"],
    "bookings": ["reservation", "booking"],
    "dog": ["pets"], "dogs": ["pets"], "cat": ["pets"], "cats": ["pets"], "pet": ["pets"],
    "smoke": ["smoking"], "smoking": ["smoke"], "cig": ["smoking"], "cigarettes": ["smoking"], "cigarette": ["smoking"],
    "wifi": ["wi-fi", "internet", "fiber"], "internet": ["wifi", "wi-fi", "fiber"],
    "breakfast": ["buffet", "morning", "dining", "food", "royal"],
    "food": ["breakfast", "restaurant", "dining", "coastal", "spice", "vegetarian", "jain"],
    "dinner": ["restaurant", "dining", "food"], "lunch": ["restaurant", "dining", "food"],
    "vegetarian": ["veg", "pure", "jain", "saffron", "restaurant", "food"],
    "jain": ["vegetarian", "veg", "saffron", "restaurant", "food"],
    "location": ["address", "candolim", "located"], "located": ["location", "address", "candolim"],
    "address": ["location", "candolim", "located"], "reach": ["location", "address", "candolim"],
    "pool": ["swimming", "infinity", "pool", "temperature"], "swimming": ["pool", "infinity"],
    "gym": ["fitness", "spa", "workout"], "workout": ["fitness", "gym", "cardio"],
    "spa": ["massage", "wellness", "fitness", "ayurveda"],
    "id": ["aadhaar", "passport", "identity", "verification", "voter"],
    "aadhaar": ["id", "identity", "verification", "passport"],
    "document": ["id", "aadhaar", "passport", "verification"],
    "documents": ["id", "aadhaar", "passport", "verification"],
    "parking": ["valet", "car", "vehicle", "ev", "charging"],
    "car": ["parking", "valet", "ev"], "vehicle": ["parking", "valet", "ev"],
    "ev": ["parking", "valet", "charging", "tata"],
    "pay": ["payment", "upi", "card", "billing", "rupay", "visa"],
    "payment": ["pay", "upi", "card", "rupay", "visa", "gst"],
    "checkin": ["arrival", "arrive", "time", "timings", "timing", "hours"],
    "checkout": ["departure", "leave", "time", "timings", "timing", "hours"],
    "timing": ["timings", "hours", "time"],
    "timings": ["timing", "hours", "time"],
    "people": ["guests", "persons", "adults", "capacity"],
    "person": ["guest", "adult"],
    "children": ["kids", "child", "bedding"],
    "kids": ["children", "child", "bedding"],
}

def normalize_text(text: str) -> str:
    t = text.lower()
    t = re.sub(r"\bcheck[\s-]+in\b", "checkin", t)
    t = re.sub(r"\bcheck[\s-]+out\b", "checkout", t)
    t = re.sub(r"\bwi[\s-]+fi\b", "wifi", t)
    return t

class HotelKnowledgeBase:
    """
    RAG-Lite In-Memory Vector Store and BM25/Cosine Retriever.
    
    Architecture Design:
    - At startup, loads and segments hotel ground truth into semantic chunks.
    - Dual-mode embedding support:
        1. Dense OpenAI Embeddings (text-embedding-3-small) if API key is present.
        2. High-precision BM25 lexical retriever with stopword elimination, compound phrase
           normalization, morphological suffix stripping, and title weighting.
    - Ensures that regardless of LLM credentials, semantic retrieval yields accurate, grounded facts.
    """
    def __init__(self, data_path: Path = HOTEL_DATA_FILE):
        self.data_path = data_path
        self.chunks: list[dict[str, Any]] = []
        self.dense_embeddings: list[list[float]] | None = None
        self._load_and_chunk()
        self._init_retriever()

    def _load_and_chunk(self):
        """Loads semantic chunks generated by SemanticHotelChunker."""
        chunker = SemanticHotelChunker(self.data_path)
        self.semantic_chunks = chunker.build_chunks()
        self.chunks = [sc.to_dict() for sc in self.semantic_chunks]

    def _init_retriever(self):
        """Initializes BM25 index and connects to Qdrant vector store."""
        self._init_bm25()
        self.vector_store = None
        try:
            from app.core.vector_store import get_vector_store
            self.vector_store = get_vector_store()
        except Exception as e:
            print(f"[RAG] Qdrant vector store initialization note: {e}")

    def _tokenize(self, text: str) -> list[str]:
        text = normalize_text(text)
        words = [w for w in re.findall(r"\b[a-zA-Z0-9_-]{2,}\b", text)]
        expanded = []
        for w in words:
            if w not in STOPWORDS:
                expanded.append(w)
                if w.endswith("ation"):
                    expanded.append(w[:-5])
                if w.endswith("ations"):
                    expanded.append(w[:-6])
                stemmed = re.sub(r"(?:ing|ed|es|s)$", "", w)
                if stemmed and len(stemmed) >= 3 and stemmed != w:
                    expanded.append(stemmed)
                if w in SYNONYMS:
                    expanded.extend(SYNONYMS[w])
        return expanded

    def _init_bm25(self):
        """Constructs an in-memory BM25 index with document frequency weights."""
        self.doc_tokens = [self._tokenize(f"{c['title']} {c['content']}") for c in self.chunks]
        self.df = Counter()
        for dt in self.doc_tokens:
            for t in set(dt):
                self.df[t] += 1

        self.N = len(self.chunks)

    def _bm25_score(self, query_tokens: list[str], idx: int) -> float:
        c = self.chunks[idx]
        title_tokens = set(self._tokenize(c["title"]))
        content_tokens = Counter(self.doc_tokens[idx])
        s = 0.0
        for t in query_tokens:
            if t in content_tokens:
                n = self.df.get(t, 0)
                # Standard BM25 IDF
                idf = math.log(1.0 + (self.N - n + 0.5) / (n + 0.5))
                # Title presence bonus
                boost = 3.0 if t in title_tokens else 1.0
                tf = content_tokens[t]
                s += idf * (tf / (tf + 1.2)) * boost
        return s

    def retrieve(self, query: str, k: int = 4, use_hyde: bool = False, use_hybrid: bool = False) -> list[dict[str, Any]]:
        """
        Retrieves top-k relevant knowledge chunks using hybrid search, dense embeddings, or BM25.
        """
        if not query or not query.strip():
            return self.chunks[:k]

        # 0. Dual-channel Hybrid Search if requested
        if use_hybrid:
            try:
                from app.core.hybrid_retriever import get_hybrid_retriever
                retriever = get_hybrid_retriever()
                results = retriever.retrieve_candidates(query, top_k=k, use_hyde=use_hyde)
                if results and len(results) >= 1:
                    return results
            except Exception as e:
                print(f"[RAG] Hybrid retrieval notice ({e}), falling back to direct channels.")

        # 1. Use Qdrant Vector Store dense retrieval if available
        if self.vector_store is not None:
            try:
                results = self.vector_store.search(query, top_k=k, use_hyde=use_hyde)
                if results and len(results) >= 1:
                    return results
            except Exception as e:
                logger_msg = f"[RAG] Vector store search failed ({e}), falling back to BM25."
                print(logger_msg)

        # 2. Local BM25 Retrieval
        q_tokens = self._tokenize(query)
        if not q_tokens:
            return self.chunks[:k]

        scored_chunks = []
        for i, c in enumerate(self.chunks):
            s = self._bm25_score(q_tokens, i)
            chunk_copy = dict(c)
            chunk_copy["score"] = round(s, 4)
            scored_chunks.append((s, chunk_copy))

        scored_chunks.sort(key=lambda x: x[0], reverse=True)
        return [item[1] for item in scored_chunks[:k]]

    def retrieve_hybrid(self, query: str, k: int = 10, use_hyde: bool = True) -> list[dict[str, Any]]:
        """Retrieves top-k candidates using dual-channel Hybrid Search (Qdrant + BM25 + RRF)."""
        from app.core.hybrid_retriever import get_hybrid_retriever
        retriever = get_hybrid_retriever()
        return retriever.retrieve_candidates(query, top_k=k, use_hyde=use_hyde)

    def retrieve_reranked(
        self,
        query: str,
        top_n: int = 3,
        candidate_k: int = 10,
        use_hyde: bool = True,
        category_filter: Optional[str] = None,
    ) -> list[dict[str, Any]]:
        """
        Two-stage retrieval pipeline:
        Stage 1: Dual-channel Hybrid Search (Qdrant + BM25 + RRF) extracts candidate_k (10) chunks.
        Stage 2: Cross-encoder reranker (NVIDIA Llama Nemotron Rerank VL 1B V2) re-scores
                 joint query-document relevance and returns top_n (3) refined chunks.
        """
        from app.core.hybrid_retriever import get_hybrid_retriever
        from app.core.reranker import get_reranker

        hybrid_retriever = get_hybrid_retriever()
        candidates = hybrid_retriever.retrieve_candidates(
            query=query,
            top_k=candidate_k,
            use_hyde=use_hyde,
            category_filter=category_filter,
        )

        reranker = get_reranker()
        return reranker.rerank(query=query, candidates=candidates, top_n=top_n)

# Singleton knowledge base instance
kb = HotelKnowledgeBase()
